# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=' ', verbose_name='내용'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=' ', help_text='포스트의 제목(최대 100자)', max_length=100, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
