# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 14:33
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170731_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
